### PR TITLE
Prepare 0.0.1.dev6 release

### PR DESCRIPTION
**Pull request by ocsw**
**What this PR does / why we need it**:
Prepare 0.0.1.dev6 release.

**Which issue(s) this PR fixes**

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ocsw** [comment]
@spotify/alf PTAL

**Review by RochesterinNYC — APPROVED** [review]
LGTM!

**Review by RochesterinNYC — CHANGES_REQUESTED** [review]
Actually, blocking approval on when `0.0.1.dev8` lands in Pypi for gordon-dns.

**Review by RochesterinNYC — APPROVED** [review]
LGTM now that `0.0.1.dev8` gordon-core is released.

**Pull request merged**
